"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Share2, Copy, Trash2, Loader2, ExternalLink, Eye, Download, Calendar } from "lucide-react";
import { formatDistanceToNow, addDays, format } from "date-fns";
import { ConfirmDialog } from "@/components/common/ConfirmDialog";
import { useDocumentShares } from "@/lib/hooks/useDocumentShares";
import type { CreateDocumentShareRequest, DocumentShareDto } from "@/types/bms";
import { toast } from "sonner";

interface DocumentSharePanelProps {
  documentId: string;
  documentName?: string;
}

export function DocumentSharePanel({
  documentId,
  documentName,
}: DocumentSharePanelProps) {
  const {
    shares,
    loading,
    loadShares,
    createShare,
    revokeShare,
  } = useDocumentShares(documentId);

  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [isCreating, setIsCreating] = useState(false);
  const [confirmRevokeId, setConfirmRevokeId] = useState<string | null>(null);
  const [expiresInDays, setExpiresInDays] = useState(7);
  const [requirePassword, setRequirePassword] = useState(true);
  const [allowDownload, setAllowDownload] = useState(true);
  const [maxAccessCount, setMaxAccessCount] = useState<number | undefined>(undefined);

  useEffect(() => {
    if (documentId) {
      loadShares();
    }
  }, [documentId, loadShares]);

  const handleCreateShare = async () => {
    setIsCreating(true);
    try {
      // Calculate expiration date from days
      const expiresAt = new Date();
      expiresAt.setDate(expiresAt.getDate() + expiresInDays);

      const request: CreateDocumentShareRequest = {
        canDownload: allowDownload,
        maxAccessCount: maxAccessCount,
        expiresAt: expiresAt.toISOString(),
        // Password will be auto-generated by server if not provided
        password: requirePassword ? undefined : null,
      };
      const result = await createShare(request);
      if (result) {
        setCreateDialogOpen(false);
        // Reset form
        setExpiresInDays(7);
        setRequirePassword(true);
        setAllowDownload(true);
        setMaxAccessCount(undefined);
      }
    } finally {
      setIsCreating(false);
    }
  };

  const handleCopyLink = (share: DocumentShareDto) => {
    if (share.shareUrl) {
      navigator.clipboard.writeText(share.shareUrl);
      toast.success("Link copied to clipboard");
    }
  };

  const handleCopyPassword = (accessToken?: string | null) => {
    if (accessToken) {
      navigator.clipboard.writeText(accessToken);
      toast.success("Access token copied to clipboard");
    }
  };

  const handleRevoke = async (shareId: string) => {
    setConfirmRevokeId(shareId);
  };

  const isExpired = (share: DocumentShareDto) => {
    if (!share.expiresAt) return false;
    return new Date(share.expiresAt) < new Date();
  };

  const isActive = (share: DocumentShareDto) => {
    return share.isActive && !isExpired(share);
  };

  return (
    <>
      <div className="bg-white dark:bg-stone-900 rounded-xl border border-stone-200 dark:border-stone-700">
        <div className="px-5 py-4 border-b border-stone-200 dark:border-stone-700 flex items-center justify-between">
          <h3 className="flex items-center gap-2 text-base font-semibold text-stone-900 dark:text-stone-50">
            <Share2 className="w-5 h-5" />
            External Shares
          </h3>
          <Button size="sm" onClick={() => setCreateDialogOpen(true)} className="bg-accent-cyan hover:bg-accent-cyan/90 text-white text-xs">
            <Share2 className="w-4 h-4 mr-1" />
            Create Share
          </Button>
        </div>
        <div className="p-5">
          {loading ? (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="w-6 h-6 animate-spin text-stone-400 dark:text-stone-500" />
            </div>
          ) : shares.length === 0 ? (
            <div className="text-center py-8 text-stone-500 dark:text-stone-400">
              No external shares created yet
            </div>
          ) : (
            <div className="space-y-3">
              {shares.map((share) => (
                <div
                  key={share.id}
                  className={`p-4 rounded-lg border ${
                    isActive(share)
                      ? "bg-emerald-50 border-emerald-200 dark:bg-emerald-950/30 dark:border-emerald-800"
                      : "bg-stone-50 border-stone-200 dark:bg-stone-800 dark:border-stone-700 opacity-60"
                  }`}
                >
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-2">
                        <Badge
                          variant={isActive(share) ? "default" : "secondary"}
                          className={isActive(share) ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-400" : ""}
                        >
                          {isActive(share) ? "Active" : isExpired(share) ? "Expired" : "Revoked"}
                        </Badge>
                        {share.hasPassword && (
                          <Badge variant="outline" className="text-xs">
                            Password Protected
                          </Badge>
                        )}
                        {share.canDownload && (
                          <Badge variant="outline" className="text-xs">
                            <Download className="w-3 h-3 mr-1" />
                            Download
                          </Badge>
                        )}
                      </div>

                      <div className="text-sm text-stone-500 dark:text-stone-400 space-y-1">
                        <div className="flex items-center gap-2">
                          <Calendar className="w-3 h-3" />
                          {share.expiresAt
                            ? `Expires ${formatDistanceToNow(new Date(share.expiresAt), { addSuffix: true })}`
                            : "No expiration"}
                        </div>
                        <div className="flex items-center gap-2">
                          <Eye className="w-3 h-3" />
                          {share.accessCount || 0} views
                          {share.maxAccessCount && ` / ${share.maxAccessCount} max`}
                        </div>
                        <div className="text-xs text-stone-400 dark:text-stone-500">
                          Created {share.createdAt
                            ? formatDistanceToNow(new Date(share.createdAt), { addSuffix: true })
                            : "recently"}
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center gap-1">
                      {isActive(share) && share.shareUrl && (
                        <>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleCopyLink(share)}
                            title="Copy link"
                          >
                            <Copy className="w-4 h-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => share.shareUrl && window.open(share.shareUrl, "_blank")}
                            title="Open link"
                          >
                            <ExternalLink className="w-4 h-4" />
                          </Button>
                        </>
                      )}
                      {isActive(share) && (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleRevoke(share.id!)}
                          className="text-red-600 hover:text-red-700"
                          title="Revoke share"
                        >
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      )}
                    </div>
                  </div>

                  {isActive(share) && share.accessToken && (
                    <div className="mt-3 pt-3 border-t border-stone-200 dark:border-stone-700">
                      <div className="flex items-center justify-between text-sm">
                        <span className="text-stone-500 dark:text-stone-400">Access Token:</span>
                        <div className="flex items-center gap-2">
                          <code className="bg-stone-100 dark:bg-stone-800 px-2 py-1 rounded text-xs text-stone-700 dark:text-stone-300">
                            {share.accessToken.slice(0, 8)}...
                          </code>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleCopyPassword(share.accessToken)}
                          >
                            <Copy className="w-3 h-3" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      <ConfirmDialog
        open={!!confirmRevokeId}
        onOpenChange={(open) => { if (!open) setConfirmRevokeId(null); }}
        title="Revoke Share Link"
        description="Are you sure you want to revoke this share link? Anyone with the link will lose access immediately."
        confirmText="Revoke"
        variant="destructive"
        icon={Trash2}
        onConfirm={async () => {
          if (confirmRevokeId) await revokeShare(confirmRevokeId);
          setConfirmRevokeId(null);
        }}
      />

      {/* Create Share Dialog */}
      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Create External Share</DialogTitle>
            <DialogDescription>
              Create a shareable link for &ldquo;{documentName || "this document"}&rdquo;
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label>Expires After</Label>
              <Select
                value={String(expiresInDays)}
                onValueChange={(value) => setExpiresInDays(parseInt(value))}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">1 day</SelectItem>
                  <SelectItem value="7">7 days</SelectItem>
                  <SelectItem value="14">14 days</SelectItem>
                  <SelectItem value="30">30 days</SelectItem>
                  <SelectItem value="90">90 days</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <Label>Require Password</Label>
                <div className="text-xs text-stone-500 dark:text-stone-400">
                  Recipient must enter password to view
                </div>
              </div>
              <Switch
                checked={requirePassword}
                onCheckedChange={setRequirePassword}
              />
            </div>

            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <Label>Allow Download</Label>
                <div className="text-xs text-stone-500 dark:text-stone-400">
                  Recipient can download the file
                </div>
              </div>
              <Switch
                checked={allowDownload}
                onCheckedChange={setAllowDownload}
              />
            </div>

            <div className="grid gap-2">
              <Label>Max Views (Optional)</Label>
              <Input
                type="number"
                placeholder="Unlimited"
                value={maxAccessCount || ""}
                onChange={(e) =>
                  setMaxAccessCount(e.target.value ? parseInt(e.target.value) : undefined)
                }
                min={1}
              />
              <div className="text-xs text-stone-500 dark:text-stone-400">
                Link will stop working after this many views
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setCreateDialogOpen(false)}
              disabled={isCreating}
            >
              Cancel
            </Button>
            <Button onClick={handleCreateShare} disabled={isCreating}>
              {isCreating ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Creating...
                </>
              ) : (
                <>
                  <Share2 className="w-4 h-4 mr-2" />
                  Create Link
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
